import {
  IconAlertTriangle,
  IconArrowRight,
  IconBell,
  IconCheck,
  type IconProps,
  IconChevronLeft,
  IconChevronRight,
  IconCommand,
  IconFile,
  IconFileText,
  IconFolder,
  IconHelpCircle,
  IconKey,
  IconLayoutDashboard,
  IconLayoutKanban,
  IconLoader2,
  IconLogin,
  IconMoon,
  IconPhoto,
  IconPlus,
  IconSettings,
  IconShield,
  IconSun,
  IconTicket,
  IconTrash,
  IconUser,
  IconUserCircle,
  IconUserEdit,
  IconUserX,
  IconUsers,
  IconX,
  IconBrandGithub,
  IconBrandTwitter,
  IconPalette,
  IconDotsVertical,
  IconDeviceLaptop,
  IconPizza
} from '@tabler/icons-react';

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  dashboard: IconLayoutDashboard,
  logo: IconCommand,
  login: IconLogin,
  close: IconX,
  palette: IconPalette,
  spinner: IconLoader2,
  kanban: IconLayoutKanban,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  trash: IconTrash,
  employee: IconUserX,
  post: IconFileText,
  page: IconFile,
  userPen: IconUserEdit,
  user2: IconUserCircle,
  media: IconPhoto,
  settings: IconSettings,
  ellipsis: IconDotsVertical,
  add: IconPlus,
  warning: IconAlertTriangle,
  user: IconUser,
  arrowRight: IconArrowRight,
  help: IconHelpCircle,
  pizza: IconPizza,
  sun: IconSun,
  moon: IconMoon,
  laptop: IconDeviceLaptop,
  github: IconBrandGithub,
  twitter: IconBrandTwitter,
  workspace: IconFolder,
  teams: IconUsers,
  account: IconUserCircle,
  profile: IconUser,
  notification: IconBell,
  ticket: IconTicket,
  shield: IconShield,
  key: IconKey,
  check: IconCheck
};
